import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import Navbar from "./_components/navbar";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "NutriCampus",
    description: "Generated by us and sum by AI... dicks",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}
            >
                {/* <Navbar /> */}
                {children}
            </body>
        </html>
    );
}
